theme: minima
title: GitHub RevOps & Enablement Perspectives
author: Betsy Matthies
description: A blog exploring the intersection of revenue, operations, and enablement, offering practical tips, leadership lessons, and industry trends from a GitHub executive.
